import type { Capability } from "./types";
import {
  browserNavigateTool,
  browserClickTool,
  browserTypeTool,
  browserScreenshotTool,
  browserExtractTool,
  browserCloseTool,
  browserSnapshotTool,
  browserWaitForTool,
  browserSelectTool,
  browserTabsTool,
  browserClearSessionTool,
  browserEvaluateTool,
  browserScrollTool,
  browserHoverTool,
  browserDragTool,
  browserCheckTool,
  browserUncheckTool,
  browserChooseFileTool,
  browserNavigateBackTool,
  browserNavigateForwardTool,
  browserReloadTool,
  browserGetCookiesTool,
  browserSetCookiesTool,
  browserDeleteCookiesTool,
  browserNetworkRequestsTool,
  browserConsoleMessagesTool,
  browserTabNewTool,
  browserTabListTool,
  browserTabSelectTool,
  browserTabCloseTool,
  browserToolPassthrough,
} from "../agent/tools/browserTools";

export const browserCapability: Capability = {
  id: "browser",
  label: "Headless Browser",
  toolGroups: ["browser"],
  tools: [
    browserNavigateTool,
    browserClickTool,
    browserTypeTool,
    browserScreenshotTool,
    browserExtractTool,
    browserCloseTool,
    browserSnapshotTool,
    browserWaitForTool,
    browserSelectTool,
    browserTabsTool,
    browserClearSessionTool,
    browserEvaluateTool,
    browserScrollTool,
    browserHoverTool,
    browserDragTool,
    browserCheckTool,
    browserUncheckTool,
    browserChooseFileTool,
    browserNavigateBackTool,
    browserNavigateForwardTool,
    browserReloadTool,
    browserGetCookiesTool,
    browserSetCookiesTool,
    browserDeleteCookiesTool,
    browserNetworkRequestsTool,
    browserConsoleMessagesTool,
    browserTabNewTool,
    browserTabListTool,
    browserTabSelectTool,
    browserTabCloseTool,
    browserToolPassthrough,
  ],
  configRequirements: [],
  async healthCheck() {
    return { healthy: true };
  },
};
