import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const routesSource = fs.readFileSync(path.resolve("server/routes.ts"), "utf8");
const routingSource = fs.readFileSync(path.resolve("server/agent/phoneRuntimeRouting.ts"), "utf8");
const runtimeToolNamesSource = fs.readFileSync(path.resolve("server/agent/androidPhoneRuntimeToolNames.ts"), "utf8");
const runtimeSource = fs.readFileSync(path.resolve("server/agent/tools/androidAppRuntime.ts"), "utf8");
const bridgeSource = fs.readFileSync(path.resolve("server/daemon/bridge.ts"), "utf8");
const androidOpHandlerSource = fs.readFileSync(path.resolve("android-daemon/app/src/main/java/com/jarvis/daemon/OpHandler.kt"), "utf8");

assert.match(routesSource, /ANDROID_PHONE_RUNTIME_TOOL_NAMES/);
assert.match(routesSource, /filterPhoneRuntimeModelTools/);
assert.match(routingSource, /function filterPhoneRuntimeModelTools/);
assert.match(routingSource, /allowDaemonActionFallback/);
assert.match(routingSource, /SERVER_YOUTUBE_TOOL_NAMES/);
assert.match(routingSource, /allowServerYoutubeTools/);
assert.match(routingSource, /if \(!name\) return false/);
assert.match(routingSource, /isAndroidPhoneRuntimeToolName\(name\)\) return true/);
assert.match(routingSource, /name === ["']daemon_action["']\)\s+return options\.allowDaemonActionFallback === true/);
assert.match(routingSource, /SERVER_YOUTUBE_TOOL_NAMES\.has\(name\)\) return options\.allowServerYoutubeTools === true/);
assert.match(routingSource, /return false;\s*\}\);/);
assert.match(routesSource, /keepDaemonActionFallback[\s\S]*focusedToolNames\.add\(["']daemon_action["']\)/);
assert.match(routesSource, /routeRequiredToolNames[\s\S]*keepDaemonActionFallback[\s\S]*\["daemon_action"\]/);
assert.match(routesSource, /const youtubeServerResearchRequest = androidActive && isYoutubeServerResearchRequest\(lastUserContent\)/);
assert.match(routesSource, /keepDaemonActionFallback[\s\S]*!youtubeServerResearchRequest/);
assert.match(routesSource, /const useFocusedRequestTools = toolAwareRoute\.shouldPreferTool \|\| routeRequiredToolNames\.length > 0/);
assert.match(routesSource, /usePhoneRuntimeToolSurfaceOnly[\s\S]*filterPhoneRuntimeModelTools\(firstTurnToolPolicy\.tools,\s*\{/);
assert.match(routesSource, /allowServerYoutubeTools:\s*youtubeServerResearchRequest/);
assert.match(routesSource, /usePhoneRuntimeToolSurfaceOnly\s*=\s*androidActive && phoneRuntimeCoveredRequest/);
assert.doesNotMatch(routesSource, /isAndroidLocalGemmaModelName/);
assert.match(routesSource, /\.\.\.ANDROID_PHONE_RUNTIME_TOOL_NAMES/);
assert.match(routingSource, /function buildPhoneRuntimeRequiredToolNames/);
assert.match(routingSource, /function deterministicPhoneRuntimeToolCallFromRequest/);
assert.match(routingSource, /android_read_notifications/);
assert.match(routesSource, /Routing notification request to Android Device Control/);
assert.match(routesSource, /deterministicAndroidToolSummary\(tc\.function\.name, execResult\)/);
assert.match(routingSource, /function isYoutubeServerResearchRequest/);
assert.match(routingSource, /function isYoutubePhoneActionRequest/);
assert.match(routingSource, /function isMemoryPhoneBypassRequest/);
assert.match(routingSource, /function isPhoneOpenActionRequest/);
assert.match(routingSource, /project\|build\|create\|make\|generate\|scaffold\|code\|website\|web\\s\+app/);
assert.match(routingSource, /function isPhoneOpenActionRequest[\s\S]*project\|build\|create[\s\S]*youtube\|you\\s\*tube/);
assert.match(routingSource, /function hasPhoneRuntimeContext/);
assert.match(routingSource, /function isPhoneRuntimeCoveredRequest/);
assert.match(routingSource, /isPhoneNotificationReadRequest\(normalized\)/);
assert.match(routingSource, /isYoutubePhoneActionRequest\(normalized\) && !isYoutubeServerResearchRequest\(normalized\)/);
assert.match(routingSource, /const youtubePhoneActionRequest = isYoutubePhoneRequest\(lastUserContent\) && isYoutubePhoneActionRequest\(lastUserContent\)/);
assert.doesNotMatch(routingSource, /\(\?:you\\s\*tube\|youtube\|yt\)\?\\s\*videos/);
assert.match(routingSource, /\(\?:you\\s\*tube\|youtube\|yt\)\\s\*videos/);
assert.match(routingSource, /return isPhoneOpenActionRequest\(normalized\) \|\|/);
assert.match(
  routingSource,
  new RegExp("hasPhoneRuntimeContext\\(normalized\\) && /\\\\b\\(\\?:tap\\|swipe\\|scroll\\|type\\|press\\|back\\|home\\|recents\\|enter\\)"),
);
assert.match(routesSource, /memoryPhoneBypassRequest[\s\S]*isPhoneRuntimeCoveredRequest\(lastUserContent\)/);
assert.match(routesSource, /phoneRuntimeCoveredRequest \|\|[\s\S]*deviceControlKeywords\.some/);
assert.doesNotMatch(routesSource, /'launch',/);
assert.doesNotMatch(routesSource, /'look it up'/);
assert.doesNotMatch(routesSource, /'find me a video'/);
assert.match(routingSource, /const youtubeResearchRequest = isYoutubeServerResearchRequest\(lastUserContent\)/);
assert.match(routingSource, /if \(!youtubeResearchRequest\)[\s\S]*requiredToolNames\.add\(["']android_youtube_search["']\)[\s\S]*\} else \{[\s\S]*requiredToolNames\.add\(["']search_youtube["']\)/);
assert.match(routingSource, /requiredToolNames\.add\(["']search_youtube["']\)/);
assert.match(routingSource, /requiredToolNames\.add\(["']fetch_youtube_transcript["']\)/);
assert.match(routesSource, /effectiveToolAwareRoute[\s\S]*priorityToolNames:\s*uniqueToolNames/);
assert.match(routesSource, /buildToolExecutionPolicy\(\{[\s\S]*route:\s*effectiveToolAwareRoute/);
assert.match(routesSource, /forceRequired:\s*isDeviceControlRequest \|\| isDiagnosticsRequest \|\| isResearchRequest \|\| routeRequiredToolNames\.length > 0/);
assert.match(routesSource, /tc\.function\.name === 'android_return_to_jarvis_chat'[\s\S]*savePendingCoachResponse/);
assert.match(routesSource, /daemonAbsoluteRuleBase/);
assert.match(routesSource, /daemon_action fallback exposed for this unsupported phone action/);
assert.match(routesSource, /treat it as a valid phone action/);
assert.match(routesSource, /Use android_notify_user, then android_return_to_jarvis_chat at the end of multi-step phone tasks/);

assert.match(runtimeToolNamesSource, /export const ANDROID_PHONE_RUNTIME_TOOL_NAMES/);
assert.match(runtimeSource, /export \{ ANDROID_PHONE_RUNTIME_TOOL_NAMES \}/);
assert.match(runtimeSource, /export const androidPhoneRuntimeTools/);
assert.match(runtimeSource, /androidOpenAppByNameTool/);
assert.match(runtimeSource, /androidCaptureScreenTool/);
assert.match(runtimeSource, /androidReadNotificationsTool/);
assert.match(runtimeSource, /\{ type: ["']android_notify["'], title, body \}/);
assert.match(runtimeSource, /galleryPersistence:\s*["']temporary_chat_preview/);
assert.match(runtimeSource, /userFacingSummary:\s*["']Attached to this chat as a temporary preview/);
assert.match(runtimeSource, /explainUnsupportedPhoneRuntimeAction/);
assert.match(routesSource, /Phone action unavailable/);
assert.match(routesSource, /buttonLabel\?:\s*string/);
assert.match(routesSource, /execResult\.buttonLabel[\s\S]*linkData\.buttonLabel = execResult\.buttonLabel/);
assert.match(runtimeSource, /fallback capture cleanup is best-effort/);
assert.doesNotMatch(runtimeSource, /savedToGallery:\s*false/);
assert.doesNotMatch(runtimeSource, /not saved to the user's gallery/i);
assert.doesNotMatch(runtimeSource, /Missing Android permissions: \$\{missing\.join/);
assert.match(runtimeSource, /Missing Android permission: android_browse/);

assert.match(bridgeSource, /\| \{ type: ["']android_notify["']; title: string; body: string \}/);
assert.match(androidOpHandlerSource, /"notify", "android_notify" -> handleNotify/);
assert.match(runtimeSource, /\{ label: ["']Camera["'], packageName: ["']com\.android\.camera2["'], aliases: \["camera"/);
assert.match(androidOpHandlerSource, /"com\.android\.camera2"\s+to listOf\("com\.sec\.android\.app\.camera", "com\.google\.android\.GoogleCamera"/);
assert.match(androidOpHandlerSource, /"com\.sec\.android\.app\.camera"\s+to listOf\("com\.android\.camera2", "com\.google\.android\.GoogleCamera"/);

console.log("All Phone Runtime tool surface assertions passed.");
